### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by shardflower** [MengLeiFudge/MLJ_DSPmods#4]
希望能把分馏塔做成可以升级的关系，方便将通用改为增殖，感谢！

**Comment by MengLeiFudge** [comment]
抱歉才看到。目前只有精准分馏塔、通用分馏塔是一二级的关系，因为它们属于同样功能且效率提升。而其他塔功能不同，所以没做升级。如果你认为有需要的话，我或许可以加一个开关来控制它？例如：
关闭：精准-通用
开启：精准-建筑-通用-点数聚集-增产
这样如何？
你可以加创世之书群（991895539）或者我的QQ（605738729）。

**Comment by MengLeiFudge** [comment]
想了一下，全部做成升级链确实更好用。没有加开关，直接改了。

**Comment by shardflower** [comment]
首先，感谢您的回复，我很抱歉，昨天没有及时回复您，感谢您能采纳我的建议，并付诸实践。谢谢您能够制作这个模组！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月16日(周四) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [MengLeiFudge/MLJ_DSPmods] 功能建议 (Issue #4)




 
想了一下，全部做成升级链确实更好用。没有加开关，直接改了。
