### ISSUE TITLE
Running Error

### ISSUE THREAD

**Issue by iGeMiNix** [MengLeiFudge/MLJ_DSPmods#6]
Hello. I am getting an error with the mod using the fractionator ironically for it's main purpose, to fractionate hydrogen into deuterium. I am using other mods. Turning them other mods off and just using this mod seems to show the error up every time on boot. I am wondering if perhaps a fix can be done before I start a new save. Thanks.

![DSPGAME_oJRZpFg03x](https://github.com/MengLeiFudge/MLJ_DSPmods/assets/29348855/b04b7881-8887-49d1-a431-99bd3c3ec4ef)

**Comment by MengLeiFudge** [comment]
Thank you for your feedback! Are you currently using version 1.3.1?
It's hard to find the bug through the image, but I've got an initial direction for troubleshooting.
Could you install [ilLine](https://thunderstore.io/c/dyson-sphere-program/p/PhantomGamers/IlLine/) to provide more detailed information? After installing, the error message shows the exact line of code, which helps me to solve the problem.
I'm in the process of troubleshooting this issue, and I'll keep you posted if I get any results.

**Comment by MengLeiFudge** [comment]
https://github.com/MengLeiFudge/MLJ_DSPmods/blob/30a6da6d7eae465ba732226c123ab271ab140a9c/FractionateEverything/src/Main/FractionatorLogic.cs#L191 I forgot to add the original deuterium fractionation to the fractionation list, then the fractionator accepting the item but not knowing what to do with it. Now I've solved it.
Thanks again for your feedback! I will push version 1.3.2 later.
