### ISSUE TITLE
Certain items not fractionating

### ISSUE THREAD

**Issue by iGeMiNix** [MengLeiFudge/MLJ_DSPmods#7]
Hello again!

It seems that with the base mod, the fractionators themselves don't fractionate to the other buildings, same with the MK1 to MK2, and MK3 sorters, at least using the building high speed fractionator which I am assuming should be the go to for these items.

When Megastructures is enabled,
Precision doesn't fractionate to high speed and high speed doesn't fractionate to universal.
Universal fractionates to Points Aggregate and to Increase Production.
MK1 sorters fractionates to MK2 sorters, but MK2 sorters do not fractionate to MK3 sorters.

I would like to know if you are able to replicate this issue. Thanks again for your mod and your quick responses to the issues.

**Comment by MengLeiFudge** [comment]
Thanks for the feedback, I have not reproduced the issue, but I can think of a few scenarios that might lead to the anomaly you describe.

First of all, I need to make one thing clear to you: if you want the Building-HighSpeed Fractionator to work, you need to unlock the corresponding fractionation recipe (the same goes for the Precision Fractionator and the Universal Fractionator, but the other two don't require a fractionation recipe). So I'm guessing that your game archive didn't unlock the corresponding recipes, so you can't fractionate them. **_Please check the archive and let me know if they are unlocked._**

Generally speaking, when a new item or building is unlocked, the corresponding fractionation recipe is unlocked at the same time. For example when you unlock Sorter MK2, you should also unlock the recipe for Sorter MK1 Fractionation to Sorter MK2. You can see exactly where certain fractionation recipes are unlocked on the tech page, but please note that tech shows up to 3 unlocked items or recipes, so it may not be possible to find certain fractionation recipes on the tech page. Don't worry, you won't be able to see them on the tech page only, and you can find the newly unlocked recipes on the fractionation page when the tech research is complete.

I'm trying to understand **_if you're using an archive that already has a portion of the tech unlocked before installing the Everything Fractionation mod_**. this is the reason I can think of for the problem. Perhaps adding the Everything Fractionation mod to an existing archive will result in the fractionation recipes for unlocked techs not unlocking again?

I will continue to troubleshoot this issue and await your feedback.

**Comment by MengLeiFudge** [comment]
Hello again! I added the following code:
```
        [HarmonyPostfix]
        [HarmonyPatch(typeof(GameHistoryData), "Import")]
        public static void ImportPostPatch() {
            foreach (TechProto t in LDB.techs.dataArray) {
                if (GameMain.history.TechUnlocked(t.ID)) {
                    foreach (int recipeID in t.UnlockRecipes) {
                        if (!GameMain.history.RecipeUnlocked(recipeID)) {
                            GameMain.history.recipeUnlocked.Add(recipeID);
                            RecipeProto r = LDB.recipes.Select(recipeID);
                            LogInfo($"Recipe {r.ID} {r.name} unlocked.");
                        }
                    }
                }
            }
        }
```
I think it will solve your problem.
Here is new dll:
[FractionateEverything_v1.3.3.zip](https://github.com/MengLeiFudge/MLJ_DSPmods/files/15367491/FractionateEverything_v1.3.3.zip)
Looking forward to your feedback. If it works, I will update version 1.3.3.

**Comment by iGeMiNix** [comment]
Hello, it seems to have fixed the issue in the base game. I did not have a chance to test it with megastructures. I appreciate the quick fix.
